Coven-Works-Inc/pkloop

src/components/home/showcase.js
Changed tagline to new requirement
fixes #17
=> Changed Tagline, fixes #17

src/App.css, src/components/auth/Register.js, src/components/header_footer/Header.js, src/components/home/faqs.js
=> FAQ functionality done

src/components/header_footer/Header.js
=> connected all links on homepage

src/App.css, src/actions/authActions.js, src/components/confirm/index.js, src/components/header_footer/Footer.js, src/components/header_footer/Header.js, src/components/home/cargo.js, src/components/home/cta_banner.js, src/components/home/works.js, src/routes.js
=> connected all buttons and links on homepage

src/App.css, src/components/confirm/index.js, src/routes.js
=> page UI done

src/actions/authActions.js
Implemeted Logout functionality with redux
Fixes #31
=> Logout functionality done

src/App.css, src/Widescreen.css, src/components/auth/Login.js, src/components/auth/Register.js
=> fixed login errors and error timeout

src/App.css, src/components/auth/Register.js
=> fixed verification link

src/components/verify/index.js
=> login page error display

src/App.css, src/components/auth/auth.css
=> faq ui fix

src/components/about/banner.css, src/components/about/index.js, src/components/pages/pages.css, src/components/pages/trust.js, src/components/pricing/index.js, src/components/pricing/pricing.css, src/components/trip/trips.css
Fix for login UI #54 
Fix for sign up UI #55 
And all other UI distortions
=> fixes #54 #55 auth pages

src/components/headerFooter/Footer.js, src/components/pages/pages.css, src/components/pages/privacy_policy.js, src/components/pages/trust.js, src/routes.js
=> Done with privacy policy page

src/components/headerFooter/Footer.js, src/components/headerFooter/header_footer.css, src/components/parcel/travel.css
=> resolves #18

src/components/about/about.css, src/components/about/index.js, src/components/headerFooter/Footer.js, src/components/headerFooter/header_footer.css
Changed the about us page content, successfully resolves #67
=> changed the about us page content

src/components/trip/index.js, src/components/trip/trips.css
=> Added Range for Travelers

src/App.css, src/components/dashboard/profile.js
dashboard edit profile ui done
=> dashboard edit profile ui

src/App.css, src/components/dashboard/balance.js, src/components/dashboard/index.js, src/components/dashboard/profile.js, src/components/dashboard/support.js
=> dashboard my balance ui

src/App.css, src/components/dashboard/index.js, src/components/dashboard/support.js, src/components/dashboard/transactions.js
=> dashboard support ui

src/components/parcel/index.js, src/components/parcel/parcel.css
=> Added a comment box to Send parcel UI

public/index.html, src/App.css, src/components/auth/Login.js, src/components/auth/Register.js, src/components/auth/auth.css, src/components/dashboard/index.js
go back ui and functionality on login and signup. fixed #70
=> go back functionality on login and signup

src/components/auth/Forgot.js, src/components/parcel/index.js
changed parcel weight to input for specific values fixed #65
=> changed parcel weight to input for specific values

src/components/trip/index.js, src/components/trip/trips.css
made transportation a dropdown #69
=> made tranportation a dropdown

src/components/home/cargo.js
Fixes #94 
Now when users log in the dashboard content changes dynamically
=> redirect users and change navigation content dynamically

src/components/parcel/index.js, src/components/parcel/travelers.js, src/countries.json
working on filter on parcel page
=> working on filter on parcel page

src/components/parcel/index.js
working on filter on parcel page 2
=> working on filter on parcel page2

src/components/parcel/prevIndex.js
=> saved former index page logic

package-lock.json, src/Countriesstate.json, src/components/common/common.css, src/components/common/modal.js, src/components/parcel/index.js, src/components/parcel/parcel.css, src/components/trip/index.js
Add JSON for state and countries
Fixed #115
=> Add JSON for state and countries

package-lock.json, public/index.html, src/Countriesstate.json, src/components/auth/Login.js, src/components/auth/Register.js, src/components/auth/auth.css, src/components/common/common.css, src/components/common/modal.js, src/components/parcel/index.js, src/components/parcel/parcel.css, src/components/trip/index.js, src/components/trip/trips.css
Fixed #117 Add modal for package weight and cost
=> Add modal for package weight

src/actions/authActions.js, src/components/auth/Login.js, src/components/trip/index.js, src/reducers/authReducer.js
Fixed #113  display error message or success on login
=> error message or redirect on login

src/components/headerFooter/header_footer.css
=> Changed states to cities

src/components/parcel/index.js
added function call to travelers component from parcel
=> added function call to travelers component from parcel

src/components/parcel/index.js, src/components/parcel/parcel.css, src/components/parcel/travel.css, src/components/payment/index.js
=> authenticated flow done

src/components/parcel/index.js, src/components/payment/index.js, src/routes.js
=> payment cost logic done

package-lock.json, package.json, src/App.js, src/components/parcel/index.js, src/utils/scrollToTop.js
scroll to top on all components mount done
=> scroll to top on all components mount done

src/routes.js
scroll to top on all components mount done2
=> scroll to top on all components mount done2

src/components/parcel/index.js
=> refactored handleParcelCost

src/components/dashboard/chat.js, src/components/dashboard/index.js, src/components/parcel/index.js, src/routes.js
=> fixed chat popup issues

src/actions/travelerActions.js, src/components/common/button.js, src/components/dashboard/chat.css, src/components/dashboard/chat.js, src/components/dashboard/index.js, src/components/parcel/index.js
payment flow to chat to payment done
=> payment flow to chat to payment done

src/components/dashboard/chat.js
payment flow to chat to payment done2
=> payment flow to chat to payment done2

src/actions/transActions.js, src/components/dashboard/transactions.js, src/reducers/transReducer.js
=> displaying users transaction

src/App.css, src/components/dashboard/profile.js, src/components/headerFooter/Header.js, src/components/trip/index.js
separate profile into picture and form
=> separate profile into picture and form

src/components/dashboard/chat.js, src/components/dashboard/index.js, src/components/dashboard/support.css, src/components/dashboard/transactions.js
edited receiver form ui for chat component
=> edited receiver form ui for chat component

src/App.css, src/Mobile.css, src/components/common/banner.js, src/components/common/common.css, src/components/faq/faq.css, src/components/faq/index.js, src/components/headerFooter/Header.js, src/components/home/cargo.css, src/components/home/cta_banner.js, src/components/howItWorks/howitworks.css, src/components/pricing/index.js, src/components/pricing/pricing.css
made home, pricing, howiworks, faqs responsive
=> made home, pricing, howiworks, faqs responsive

src/routes.js
capitalized auth component file names
=> capitalized auth component file names

src/App.css, src/components/dashboard/balance.js, src/components/dashboard/header.js, src/components/dashboard/redeem.js, src/routes.js
=> ui for redeem code

src/App.css, src/components/dashboard/header.js, src/components/dashboard/tips.js, src/routes.js
=> ui for tips

src/App.css, src/Mobile.css, src/components/about/index.js, src/components/headerFooter/footer.css, src/components/headerFooter/header_footer.css
=> responsiveness for some pages

src/components/auth/Register.js, src/components/auth/auth.css, src/components/faq/faq.css, src/components/faq/index.js, src/components/howItWorks/index.js, src/components/pages/pages.css, src/components/pages/tos.js, src/components/parcel/index.js, src/components/pricing/index.js
=> fixed all UI bug reports

src/App.css, src/components/faq/index.js
made verify component responsive
=> made verify component responsive

src/App.css, src/actions/authActions.js, src/components/headerFooter/Header.js, src/components/headerFooter/header_footer.css
added beta tag and cleaned up balance component
=> added beta tag and cleaned up balance component

src/Widescreen.css, src/components/headerFooter/Footer.js, src/components/headerFooter/Header.js, src/components/headerFooter/header_footer.css, src/components/verify/index.js
moved some links from the header to footer
=> moved some links from the header to footer

src/Mobile.css
made list trip page mobile responsive
=> made list trip page mobile responsive

src/components/trip/index.js
timing on successful trip creation removed
=> timing on successful trip creation removed
